Core/urls.py
from Core.models import Contact
from django.urls import path
from . import views

app_name = 'Core'
urlpatterns = [
    
    path('',views.index , name="index"),
    path('api/contact' , views.ContactData , name = "ContactForm"),
    path('api/work' , views.worksData , name = "worksData"),
    path('api/work-details/<int:pk>/' , views.workDetails ,name = "workDetaile" )
   
]

MahdyWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Core.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/models.py
from django.db import models
from django.db.models.fields import CharField, DateField

# Create your models here.

class Home(models.Model):
   name =  models.CharField(  null = True , blank=True , max_length=50 , verbose_name = "الاسم الخاص بي")
   slogan = models.CharField( null = True , blank=True , max_length=50, verbose_name = "الشعار")
   background = models.ImageField( null = True , blank=True , verbose_name = "الخلفية الاساسية")

   facbook = models.CharField(  null = True , blank=True ,max_length=200 , verbose_name = "facbook" )
   linked_in = models.CharField( null = True , blank=True , max_length=200 , verbose_name = "linked_in" )
   git_hub = models.CharField( null = True , blank=True , max_length=200 , verbose_name = "git_hub" )
   instagram = models.CharField( null = True , blank=True , max_length=200 , verbose_name = "instagram" )
   behance = models.CharField( null = True , blank=True , max_length=200 , verbose_name = "behance" )

   def __str__(self) :
      return self.name
   

class About(models.Model):
  job_title = models.CharField(max_length=50, verbose_name = "عنوان الوظيفة" , null = True ,blank=True)
  job_discraption = models.TextField( verbose_name = "تفاصيل العمل" , null = True ,blank=True)
  website = models.CharField(max_length=50, verbose_name = "الموقع" , null = True ,blank=True)
  city = models.CharField(max_length=15, verbose_name = "المدينة" , null = True ,blank=True)
  age = models.IntegerField(verbose_name="السن" , null = True ,blank=True)
  phone = models.CharField(max_length=20,verbose_name="رقم الموبيل" , null = True ,blank=True)
  degree = models.CharField(max_length=20, verbose_name = "الدرجة العلمية" , null = True ,blank=True)
  birthday = models.DateField(auto_now=False, auto_now_add=False , verbose_name="تاريخ الميلاد" , null = True ,blank=True)
  my_discraption = models.TextField( verbose_name = "تفاصيل شخصية" , null = True ,blank=True)
  freelancer = models.BooleanField(default=True , verbose_name="متاح للعمل الحر" , null = True ,blank=True)
  image = models.ImageField(verbose_name="الصورة" , null = True ,blank=True)

  def __str__(self):
      return self.job_title
       

class Counter(models.Model):
   happy_client =models.IntegerField(verbose_name = "عدد العملاء")
   projects =models.IntegerField(verbose_name = "عدد المشاريع")
   courses =models.IntegerField(verbose_name = "عدد الكورسات")
   certifications =models.IntegerField(verbose_name = "عدد الشهادات")

class Skills(models.Model):
   title = models.CharField(max_length=50 , verbose_name="المهارة")
   avarage = models.IntegerField(verbose_name="النسبة")

   def __str__(self):
       return self.title


class INTEREST(models.Model):
   icons = models.CharField( max_length=200 , verbose_name = "icons")
   title = models.CharField( max_length=50 , verbose_name = "العنوان")
   

   def __str__(self):
      return self.title       


class Contact(models.Model):
   name = models.CharField(max_length=50)
   email = models.EmailField()
   subject = models.CharField(max_length=100)
   message = models.TextField()
   deleted  = models.BooleanField(default=False)

   def __str__(self):
      return self.name


class Sumary(models.Model):
   title = models.CharField(max_length=100 , verbose_name = "العنوان")
   sumary = models.TextField(verbose_name = "الملخص")
   lists = models.CharField(max_length=50 , null=True , )

   def __str__(self):
          return self.title

class Eduction(models.Model):
   title = models.CharField(max_length=50 , verbose_name="العنوان")
   from_date = models.DateField()
   to_date = models.DateField()
   heading = models.CharField( max_length=100)
   discraption = models.TextField()

   def __str__(self):
      return self.title

class Experince(models.Model):
   title = models.CharField(max_length=50)
   company = models.CharField(max_length=50)
   from_date = models.CharField(max_length=50)
   to_date =  models.CharField(max_length=50)
   work_discraption = models.TextField()

   def __str__(self):
      return self.title      


class Services(models.Model):
   title = models.CharField(max_length=50)
   icons = models.CharField(max_length=50)
   discraption = models.TextField()

   def __str__(self):
      return self.title      

class Category(models.Model):
   name = models.CharField( max_length=50)   

   def __str__(self):
      return self.name   

class Works(models.Model):
   slide1 = models.ImageField(upload_to='works/' , null=True , blank=True)
   slide2 = models.ImageField(upload_to='works/', null = True , blank = True)
   slide3 = models.ImageField(upload_to='works/', null = True , blank = True)
   slide4 = models.ImageField(upload_to='works/', null = True , blank = True)
   slide5 = models.ImageField(upload_to='works/', null = True , blank = True)
   model_image = models.ImageField(upload_to='works/', )
   name = models.CharField( max_length=50)
   category = models.ForeignKey(Category,on_delete=models.CASCADE)
   client = models.CharField( max_length=50)
   project_date =models.DateField( auto_now=False, auto_now_add=False)
   project_url = models.CharField( max_length=100)
   discraption = models.TextField()
   git_hub = models.CharField( null=True ,max_length=50)

   def __str__(self):
      return self.name
   
class Testimonial(models.Model):
   name = models.CharField( max_length=50)
   job = models.CharField( max_length=50)
   image = models.ImageField(upload_to='client/', height_field=None, width_field=None, max_length=None)
   message = models.TextField()

   def __str__(self):
      return self.name
   

Core/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {

            'name' : forms.TextInput(attrs={'class' : 'form-control' ,'id':'name' ,'placeholder':'Your Name'}) , 

            'email' : forms.EmailInput(attrs={'class' : 'form-control' , 'name' : 'email' , 'id' : 'email' , 'placholder' : 'Yor Email Here','data-rule' : 'email' , 'data-msg' : 'please enter a valid email'}) , 

            'subject' : forms.TextInput(attrs={'class' : 'form-control' , 'name' : 'subject' , 'id' : 'subject' , 'placholder' : 'subject','data-rule' : 'minlen:4' , 'data-msg' : 'Please enter at least 8 chars of subject'}),

            'message' : forms.Textarea(attrs={'class' : 'form-control' , 'name' : 'message' ,'rows' : '5', 'id' : 'message' , 'placholder' : 'Message','data-rule' : 'required' , 'data-msg' : 'Please write something for us'}),

            'deleted' : forms.HiddenInput()

        }

Core/views.py
from django.http import response
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render
from .models import * 
from .forms import *
from django.contrib import messages

# Create your views here.

def index (request):
    homePage = Home.objects.all().last()
    about= About.objects.all().last()
    counter = Counter.objects.all().last()
    skills = Skills.objects.all()
    interest = INTEREST.objects.all()
    sumary = Sumary.objects.all().last()
    education = Eduction.objects.all().order_by("-id")
    experince = Experince.objects.all().order_by("-id")
    services = Services.objects.all()
    allworks = Works.objects.all()
    
    print(sumary)

    form = ContactForm()


    context = {
        'homepage': homePage,
        'about' : about,
        'counter' : counter,
        'skills' : skills,
        'interest' : interest,
        'sam' : sumary , 
        'edu' : education,
        'ex' :experince,
        'ser' : services,
        'form' : form,
        'allworks' : allworks
        
    }
    return render(request, 'Core/index.html' , context )
    

def ContactData(request):
    if request.is_ajax():
        name =request.POST.get('name' , None) # getting data from name input 
        email =request.POST.get('email' , None) # getting data from email
        subject =request.POST.get('subject' , None) # getting data from subject input 
        message =request.POST.get('message' , None) # getting data from message input 
        if name and email and subject and message:  # checking if name and email and subject and message have value
            data = Contact(
                name = name,
                email = email,
                subject = subject,
                message = message
            )
            data.save()
            response = {
                'msg' : 'Send Successfully'
            }
            return JsonResponse(response)


def worksData(request):
    if request.is_ajax():
        allworks = Works.objects.all()
        response = {
            'allworks' :allworks
        }
        return render(request , 'Core/allworks.html' ,response)

def workDetails(request , pk):
    work = Works.objects.get(id=pk)
    return render(request , 'Core/work.html' ,{'work':work})

Core/templates/Core/filter using ajax.html
      <div class="row">
        <div class="col-lg-12 d-flex justify-content-center" >
          <ul id="portfolio-flters">

            <!-- All works -->
            <li id="all" class="filter-active">
              <Form id="allworksform" method="POST">
                  <a  type="submit"  name="submit" >All </a>
              </Form>
               <!-- Ajax filter for all works -->
            <script>
    
              $('#all').on('click' , function(e){
    
                e.preventDefault();
    
                  $.ajax({
                    type : "POST",
                      url: "{% url 'Core:worksData' %}",
                      data : {
                        
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        dataType: "json",
                      },
                      success: function (res) {
                        console.log("done");
                        $( '.allWorks' ).html( '&nbsp;' ).load( "{% url 'Core:worksData' %}");
                          
                      }
                  });
            
    
              });  
    
            </script>           
            </li>
              <!-- End all works -->

              <!-- Ajax filter for webdesign -->
              <li id="design">
                <Form  method="POST">
                    <a  type="submit"  name="submit" >Web Design </a>
                </Form>
                 <!-- Ajax filter for all works -->
              <script>
      
                $('#design').on('click' , function(e){
      
                  e.preventDefault();
      
                    $.ajax({
                      type : "POST",
                        url: "{% url 'Core:webDesign' %}",
                        data : {
                          
                          csrfmiddlewaretoken: '{{ csrf_token }}',
                          dataType: "json",
                        },
                        success: function (res) {
                          console.log("webdesign");
                          $( '.allWorks' ).html( '&nbsp;' ).load( "{% url 'Core:webDesign' %}");
                            
                        }
                    });
              
      
                });  
      
              </script>           
              </li>
              <!-- End web design -->

           <!-- Ajax filter for webdesign -->
           <li id="webappliction">
            <Form  method="POST">
                <a  type="submit"  name="submit" >Web Applications </a>
            </Form>
             <!-- Ajax filter for all works -->
          <script>
  
            $('#webapplication').on('click' , function(e){
  
              e.preventDefault();
  
                $.ajax({
                  type : "POST",
                    url: "{% url 'Core:webApplications' %}",
                    data : {
                      
                      csrfmiddlewaretoken: '{{ csrf_token }}',
                      dataType: "json",
                    },
                    success: function (res) {
                      console.log("webApplications");
                      $( '.allWorks' ).html( '&nbsp;' ).load( "{% url 'Core:webApplications' %}");
                        
                    }
                });
          
  
            });  
  
          </script>           
          </li>
          <!-- End web design -->

            <li >
              <a>ERP&CRM System</a>
            </li>

            <li >
              <a>UI&UX </a>
            </li>
            
            <li >
              <a>Grpahic Design</a>
            </li>
            
          </ul>
        </div>
      </div>

      <div class="row portfolio-container" >

        {% for x in allworks  %}
        <div class="col-lg-4 col-md-6 portfolio-item ">
          <div class="portfolio-wrap">
            <img src="{{x.model_image.url}}" style="width: 340px; height:255px"class="img-fluid" alt="">
            <div class="portfolio-info">
              <h4>{{x.name}}</h4>
              <p>{{x.category}}</p>
              <div class="portfolio-links">
                <a href="{{x.model_image.url}}" data-gall="portfolioGallery" class="venobox" title="App 1"><i class="bx bx-plus"></i></a>
                <a href="portfolio-details.html" data-gall="portfolioDetailsGallery" data-vbtype="iframe" class="venobox" title="Portfolio Details"><i class="bx bx-link"></i></a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>

Core/templates/Core/work.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{{work.name}}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/assets/img/favicon.png" rel="icon">
  <link href="/static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="/static/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/venobox/venobox.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/assets/css/style.css" rel="stylesheet">

 
</head>

<body>

  <main id="main">

    <!-- ======= Portfolio Details ======= -->
    <div id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row">

          <div class="col-lg-8">
            <h2 class="portfolio-title">{{work.name}}</h2>
            <div class="owl-carousel portfolio-details-carousel">
              <img src="{{work.slide1.url}}" style="width: 800px; height:463px" class="img-fluid" alt="">
              <img src="{{work.slide2.url}}" style="width: 800px; height:463px" class="img-fluid" alt="">
              <img src="{{work.slide3.url}}" style="width: 800px; height:463px" class="img-fluid" alt="">
              <img src="{{work.slide4.url}}" style="width: 800px; height:463px" class="img-fluid" alt="">
              <img src="{{work.slide5.url}}" style="width: 800px; height:463px" class="img-fluid" alt="">

              
            </div>
          </div>

          <div class="col-lg-4 portfolio-info">
            <h3>Project information</h3>
            <ul>
              <li><strong>Category</strong>: {{work.category}}</li>
              <li><strong>Client</strong>: {{work.client}}</li>
              <li><strong>Project date</strong>: {{work.project_date}}</li>
              <li><strong>Project URL</strong>: <a href="{{work.url}}">URL</a></li>
            </ul>

            <p>
              {{work.discraption}}
            </p>
          </div>

        </div>

      </div>
    </div><!-- End Portfolio Details -->

  </main><!-- End #main -->


  <!-- Vendor JS Files -->
  <script src="/static/assets/vendor/jquery/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="/static/assets/vendor/php-email-form/validate.js"></script>
  <script src="/static/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="/static/assets/vendor/counterup/counterup.min.js"></script>
  <script src="/static/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="/static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/assets/vendor/venobox/venobox.min.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/assets/js/main.js"></script>

</body>

</html>